# Chargement des données

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Import libraries
import pandas as pd
import numpy as np
from pathlib import Path
import os

def load_data(src_path, click_path):
    '''
    Fonction utilisée pour charger les données du site "News Portal" de Globo.com

    Parameters:
        src_path : chemin vers le dossier contenant les metadonnées et la matrice embedding des articles
        click_path : chemin vers le dossier contenant les fichiers d'interactions des utilisateurs (1 fichier par heure)
    
    Returns:
        articles (dataframe) : les métadonnées des articles (id, catégorie, date de publication, nombre de mots)
        embeddings (array) : matrice de 250 vecteurs des mots contenus dans les articles
        clicks (dataframe)  : les interactions ou clicks des utilisateurs avec les articles
    '''

    # Load articles' metadata
    articles = pd.read_csv(src_path / 'articles_metadata.csv')
    # Drop useless feature
    articles.drop(columns=['publisher_id'], inplace=True)
    # Convert all data types to integer
    articles = articles.astype(np.int64)

    # Load articles' embedding
    embeddings = pd.read_pickle(src_path / 'articles_embeddings.pickle')
    # Change data type from float64 to float32
    embeddings = embeddings.astype(np.float32)

    # Load user interactions with articles
    clicks = pd.DataFrame().append([pd.read_csv(click_path / file) for file in sorted(os.listdir(click_path))],ignore_index=True)
    # Rename columns
    clicks.rename(columns={'click_article_id':'article_id'}, inplace=True)
    # Drop useless feature
    clicks.drop(columns=['click_environment', 'click_deviceGroup', 'click_os', 'click_country', 'click_region', 'click_referrer_type'], inplace=True)
    # Convert all data types to integer
    clicks = clicks.astype(np.int64)

    return articles, embeddings, clicks

In [3]:
# Set general configurations
src_path = Path('/content/drive/MyDrive/P9/Data')
click_path = Path('/content/drive/MyDrive/P9/Data/clicks/clicks')

# Call the function to load data
articles, embeddings, clicks = load_data(src_path, click_path)

# Display shape
print('Articles Dataframe shape: ', articles.shape)
print('Embedding Matrix shape: ', embeddings.shape)
print('Clicks Dataframe shape: ', clicks.shape)

Articles Dataframe shape:  (364047, 4)
Embedding Matrix shape:  (364047, 250)
Clicks Dataframe shape:  (2988181, 6)

In [4]:
# Display DF shape and 5 first rows
print('Articles Dataframe shape: ', articles.shape)
articles.head()

Articles Dataframe shape:  (364047, 4)

   article_id  category_id  created_at_ts  words_count
0           0            0  1513144419000          168
1           1            1  1405341936000          189
2           2            1  1408667706000          250
3           3            1  1408468313000          230
4           4            1  1407071171000          162

In [5]:
# Display DF shape and 5 first rows
df_embeddings = pd.DataFrame(embeddings)
print('Embedding Matrix shape: ', embeddings.shape)
df_embeddings.head()

Embedding Matrix shape:  (364047, 250)

        0         1         2    ...       247       248       249
0 -0.161183 -0.957233 -0.137944  ... -0.231686  0.597416  0.409623
1 -0.523216 -0.974058  0.738608  ...  0.182828  0.397090 -0.834364
2 -0.619619 -0.972960 -0.207360  ... -0.447580  0.805932 -0.285284
3 -0.740843 -0.975749  0.391698  ... -0.537838  0.243541 -0.885329
4 -0.279052 -0.972315  0.685374  ... -0.424061  0.185484 -0.580292

[5 rows x 250 columns]

In [6]:
# Display DF shape and 5 first rows
print('Clicks Dataframe shape: ', clicks.shape)
clicks.head()

Clicks Dataframe shape:  (2988181, 6)

   user_id        session_id  ...  article_id  click_timestamp
0        0  1506825423271737  ...      157541    1506826828020
1        0  1506825423271737  ...       68866    1506826858020
2        1  1506825426267738  ...      235840    1506827017951
3        1  1506825426267738  ...       96663    1506827047951
4        2  1506825435299739  ...      119592    1506827090575

[5 rows x 6 columns]

## Recommandation personnalisé type content-based

In [7]:
# Import libraries
import pandas as pd
import numpy as np
from time import time
from random import randint
from sklearn.metrics.pairwise import cosine_similarity

def get_ContentBased_Reco(userID, clicks, embeddings, n_reco=5):
    '''Return 5 recommended articles ID to user'''

    # Print targetted UserID
    print('Le n° d\'utilisateur est: ', userID)

    # Get the list of articles viewed by the user
    var = clicks.loc[clicks.user_id == userID]['article_id'].to_list()
    
    # Select the last element of the list (most recent one)
    value = var[-1]
    print('Le dernier article vu par l\'utilisateur est: ', value)
    
    # Delete already viewed articles except the selected one
    emb = embeddings
    for i in range (0, len(var)):
        if i != value:
            emb = np.delete(emb, [i], 0)
    
    # Delete selected article from the new matrix
    temp = np.delete(emb, [value], 0)

    # Get n_reco articles which are the most similar to the selected one
    distances = cosine_similarity([emb[value]], temp)[0]
    
    # Find the indexes, except the selected article
    ranked_ids = np.argsort(distances)[::-1][0:n_reco]
    ranked_similarities = np.sort(distances)[::-1][0:n_reco]
    print('Les articles recommandés sont: ')
    
    
    return ranked_ids.tolist()# , ranked_similarities.tolist()

In [8]:
# Call the function
start = time()

userID = 0
reco = get_ContentBased_Reco(userID, clicks, embeddings, n_reco=5)
print(reco)

print(f'Modèle exécuté en {round(time() - start, 2)}s')

Le n° d'utilisateur est:  0
Le dernier article vu par l'utilisateur est:  87205
Les articles recommandés sont:
[102720, 100020, 102412, 102611, 86703]
Modèle exécuté en 1.48s

## Recommandations personnalisé type collaborative filtering

In [11]:
pip install --upgrade pip

Requirement already satisfied: pip in /usr/local/lib/python3.7/dist-packages (21.1.3)
Collecting pip
  Downloading pip-22.0.3-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 13.3 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.3
    Uninstalling pip-21.1.3:
      Successfully uninstalled pip-21.1.3
Successfully installed pip-22.0.3

In [12]:
from IPython.display import clear_output

# Install a library
!pip install implicit

clear_output()

In [10]:
# Import libraries
import pandas as pd
import numpy as np
from time import time
from scipy.sparse import csr_matrix
from implicit.als import AlternatingLeastSquares as ALS
from implicit.lmf import LogisticMatrixFactorization as LMF

def get_CollabFilter_Reco(clicks, userID, model='ALS', n_reco=5):

    start = time()

    # Create interaction DF (count of interactions between users and articles)
    interactions = clicks.groupby(['user_id','article_id']).size().reset_index(name='count')
    # print('Interactions DF shape: ', interactions.shape)

    # csr = compressed sparse row (good format for math operations with row slicing)
    # Create sparse matrix of shape (number_items, number_user)
    csr_item_user = csr_matrix((interactions['count'].astype(float),
                                (interactions['article_id'],
                                 interactions['user_id'])))
    # print('CSR Shape (number_items, number_user): ', csr_item_user.shape)
    
    # Create sparse matrix of shape (number_user, number_items)
    csr_user_item = csr_matrix((interactions['count'].astype(float),
                                (interactions['user_id'],
                                 interactions['article_id'])))
    # print('CSR Shape (number_user, number_items): ', csr_user_item.shape)

    # Train the model on sparse matrix of shape (number_items, number_user)

    if model == 'ALS':
        # factors (int) : number of latent factors to compute
        # regularization (float) : regularization factor to use
        # iterations (int) : number of ALS iterations to use when fitting data
        # random_state (int) : seed the initial item and user factors (default:None)
        model = ALS(factors=128, regularization=0.01, iterations=30, random_state=42)
        # Calculate the confidence for each value in the data
        # low confidence level for non-read articles
        # high confidence level for read articles
        ALPHA_VAL = 40
        confidence = (csr_item_user * ALPHA_VAL).astype('double')
        model.fit(confidence)

    elif model == 'LMF':
        model = LMF(factors= 128, random_state=42)
        # model.approximate_similar_items = False
        model.fit(csr_item_user)

    # Recommend N best items from sparse matrix of shape (number_user, number_items)
    # Implicit built-in method
    # N (int) : number of results to return
    # filter_already_liked_items (bool) : if true, don't return items present in 
      # the training set that were rated/viewd by the specified user
    recommendations_list = []
    recommendations = model.recommend(userID, csr_user_item, N=n_reco, filter_already_liked_items=True)
    
    # Display i (items), not j (confidence score)
    for i, j in recommendations:
        recommendations_list.append(i)
    recommendations_list

    print(f'Completed in {round(time() - start, 2)}s')
    return recommendations_list

ModuleNotFoundError: ignored

In [ ]:
# Call the function
userID = 0
get_CollabFilter_Reco(clicks, userID=0, model='ALS', n_reco=5)

In [ ]:
# Call the function
userID = 0
get_CollabFilter_Reco(clicks, userID=0, model='LMF', n_reco=5)